// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aslzygbjxnrcvisapjfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzbHp5Z2JqeG5yY3Zpc2FwamZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjAyNjgsImV4cCI6MjA2NTEzNjI2OH0.VD0Me1-s66hTbGUeVumwMFubreFZy9mZZGuVC9nlbts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);